import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "조미미 일잘러 만들기 프로젝트",
  description: "Generated by 서동현",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
